language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x gradlew
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-de
env:
  LANG=de_DE.UTF-8
  LC_ALL=de_DE.UTF-8